### ISSUE TITLE
Random Data: crash on junk input parameters

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-educational#117]
##### Educational version

0.4.0

##### Orange version

3.30.dev

##### Expected behavior
No crash.

##### Actual behavior
Widget crashes with silly strange parameters.

```
---------------------------- ValueError Exception -----------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-educational/orangecontrib/educational/widgets/owrandomdata.py", line 477, in generate
    parts = tuple(e.generate_data(self.n_instances) if attr else None
  File "/Users/ajda/orange/orange3-educational/orangecontrib/educational/widgets/owrandomdata.py", line 477, in <genexpr>
    parts = tuple(e.generate_data(self.n_instances) if attr else None
  File "/Users/ajda/orange/orange3-educational/orangecontrib/educational/widgets/owrandomdata.py", line 161, in generate_data
    parameters = self.get_parameters()
  File "/Users/ajda/orange/orange3-educational/orangecontrib/educational/widgets/owrandomdata.py", line 142, in get_parameters
    return {name: self.get(name) for name in self.edits}
  File "/Users/ajda/orange/orange3-educational/orangecontrib/educational/widgets/owrandomdata.py", line 142, in <dictcomp>
    return {name: self.get(name) for name in self.edits}
  File "/Users/ajda/orange/orange3-educational/orangecontrib/educational/widgets/owrandomdata.py", line 139, in get
    return edit.convert(edit.text())
  File "/Users/ajda/orange/orange3-educational/orangecontrib/educational/widgets/owrandomdata.py", line 37, in convert
    return float(s)
ValueError: could not convert string to float: '1.e'
-------------------------------------------------------------------------------
```

##### Steps to reproduce the behavior
Random Data. Set `1.e` as variance.

##### Additional info (worksheets, data, screenshots, ...)
We could perhaps write a util for testing that would test text entry fields with various things, i.e. decimal points and commas, characters (special and regular), etc. Anyone missing static typing? 😅 

p.s. @lanzagar informed me it is possible to set the input type for text edits. We should do that here, I reckon.

**Comment by janezd** [comment]
> p.s. @lanzagar informed me it is possible to set the input type for text edits. We should do that here, I reckon.

If you think this widget does not set validators for edit lines, try typing `1.f` instead of `1.e`. :)

`1.e` is allowed as intermediate input for `1.e1`, which would be valid. Same with `1.`, which was fixed in #116. (See https://doc.qt.io/qt-5/qvalidator.html#validate).

This is of course still a bug, and we may have similar problems in other widgets that rely on validators in a similar way.
